---

services:

  tftpd:
    image: dreknix/pxe-tftpd:latest
    container_name: pxe-tftpd
    volumes:
      - pxe-tftpboot:/tftpboot
    network_mode: host
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - SYS_CHROOT
      - NET_BIND_SERVICE

  httpd:
    image: dreknix/pxe-httpd:latest
    container_name: pxe-httpd
    volumes:
      - pxe-www:/www
      - ./config_local.json:/config_local.json
    ports:
      - 8069:8069
    cap_drop:
      - ALL

volumes:
  pxe-tftpboot:
    external: true
  pxe-www:
    external: true

...
